

"""add_users_gender_age_group

Revision ID: 4d87d15135bd
Revises: e3c4b5a6d7f8
Create Date: 2026-01-09 13:36:23.957387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d87d15135bd'
down_revision: Union[str, None] = 'e3c4b5a6d7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.String(length=32), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('admin', 'partner', 'user', name='userrole', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'partner', 'user', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('age_group')
        batch_op.drop_column('gender')

    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partner_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_datetime', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('age_group', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('notify_users', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('photo_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('channel_message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('auto_message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_events_fingerprint'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_partner_user_id'), ['partner_user_id'], unique=False)

    op.create_table('event_interesting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('adv_placement_date', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('adv_channel_username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('adv_placement_price', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('adv_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_registered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('receipt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_interesting_pkey1')),
    sa.UniqueConstraint('event_id', 'user_id', name=op.f('uq_event_interesting'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('event_interesting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_interesting_event_id'), ['event_id'], unique=False)

    op.create_table('adv_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placement_date', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('channel_username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('placement_price', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('interesting_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('register_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('paid_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('confirmed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('adv_stats_pkey1')),
    sa.UniqueConstraint('event_id', 'placement_date', 'channel_username', 'placement_price', name=op.f('uq_adv_stats_event_date_channel_price'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
