

"""add_users_gender_age_group

Revision ID: 56fe0e2e5167
Revises: e3c4b5a6d7f8
Create Date: 2026-01-08 15:15:45.465400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '56fe0e2e5167'
down_revision: Union[str, None] = 'e3c4b5a6d7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age_group')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
