from aiogram_dialog import Dialog, StartMode, Window
from aiogram_dialog.widgets.kbd import Button, Group, Row, ScrollingGroup, Select, Start, Url
from aiogram_dialog.widgets.media import DynamicMedia
from aiogram_dialog.widgets.text import Format

from app.bot.dialogs.start.getters import (
    get_admin_event_details,
    get_admin_event_registrations,
    get_admin_events,
    get_admin_registration_pending,
    get_admin_registration_pending_details,
    get_hello,
    get_user_event_details,
    get_user_events,
)
from app.bot.dialogs.start.handlers import (
    approve_pending_registration,
    back_to_admin_registration_pending_list,
    back_to_start,
    back_to_user_events_list,
    decline_pending_registration,
    show_admin_registration_pending_list,
    show_next_user_events_page,
    show_pending_registration_details,
    show_prev_user_events_page,
    show_user_event_details,
    show_user_events_list,
    show_admin_events_list,
    show_admin_event_details,
    show_admin_event_registrations,
    show_admin_event_registration_details,
    back_to_admin_events_list,
    back_to_admin_event_details,
)
from app.bot.states.events import EventsSG
from app.bot.states.start import StartSG

start_dialog = Dialog(
    Window(
        Format("{hello}"),
        Start(
            text=Format("{create_event_button}"),
            id="start_event_creation",
            state=EventsSG.name,
            mode=StartMode.NORMAL,
            when="can_create_event",
        ),
        Button(
            text=Format("{user_events_list_button}"),
            id="user_events_list",
            on_click=show_user_events_list,
            when="can_view_user_events",
        ),
        Button(
            text=Format("{admin_events_button}"),
            id="admin_events_list",
            on_click=show_admin_events_list,
            when="can_manage_pending_registrations",
        ),
        Button(
            text=Format("{admin_pending_button}"),
            id="admin_pending_list",
            on_click=show_admin_registration_pending_list,
            when="can_manage_pending_registrations",
        ),
        getter=get_hello,
        state=StartSG.start,
    ),
    Window(
        Format("{user_events_title}"),
        Format("{user_events_empty}", when="show_user_events_empty"),
        ScrollingGroup(
            Select(
                Format("{item[0]}"),
                id="user_events_select",
                item_id_getter=lambda item: item[1],
                items="user_event_items",
                on_click=show_user_event_details,
            ),
            id="user_events_scroll",
            width=1,
            height=5,
            hide_on_single_page=True,
            when="has_user_events",
        ),
        Format("{user_events_page_text}", when="show_user_events_page"),
        Row(
            Button(
                text=Format("{user_events_prev_button}"),
                id="user_events_prev_page",
                on_click=show_prev_user_events_page,
                when="has_user_prev_page",
            ),
            Button(
                text=Format("{user_events_next_button}"),
                id="user_events_next_page",
                on_click=show_next_user_events_page,
                when="has_user_next_page",
            ),
            when="show_user_events_page",
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="user_events_back",
                on_click=back_to_start,
            ),
        ),
        getter=get_user_events,
        state=StartSG.user_events_list,
    ),
    Window(
        DynamicMedia("event_media"),
        Format("{event_details_text}"),
        Group(
            Url(
                text=Format("{view_post_button}"),
                url=Format("{event_post_url}"),
                id="user_event_view_post",
                when="has_post_url",
            ),
            Url(
                text=Format("{view_chat_button}"),
                url=Format("{event_chat_url}"),
                id="user_event_view_chat",
                when="has_chat_url",
            ),
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="user_event_back",
                on_click=back_to_user_events_list,
            ),
        ),
    getter=get_user_event_details,
    state=StartSG.user_event_details,
),
    Window(
        Format("{title}"),
        Format("{empty_text}", when="not has_items"),
        ScrollingGroup(
            Select(
                Format("{item[0]}"),
                id="admin_events_select",
                item_id_getter=lambda item: item[1],
                items="items",
                on_click=show_admin_event_details,
            ),
            id="admin_events_scroll",
            width=1,
            height=5,
            hide_on_single_page=True,
            when="has_items",
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="admin_events_back",
                on_click=back_to_start,
            ),
        ),
        getter=get_admin_events,
        state=StartSG.admin_events_list,
    ),
    Window(
        DynamicMedia("event_media"),
        Format("{event_details_text}"),
        Group(
            Url(
                text=Format("{view_post_button}"),
                url=Format("{event_post_url}"),
                id="admin_event_view_post",
                when="has_post_url",
            ),
            Url(
                text=Format("{view_chat_button}"),
                url=Format("{event_chat_url}"),
                id="admin_event_view_chat",
                when="has_chat_url",
            ),
        ),
        Row(
            Button(
                text=Format("{registrations_button}"),
                id="admin_event_registrations",
                on_click=show_admin_event_registrations,
            ),
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="admin_event_back",
                on_click=back_to_admin_events_list,
            ),
        ),
        getter=get_admin_event_details,
        state=StartSG.admin_event_details,
    ),
    Window(
        Format("{title}"),
        Format("{empty_text}", when="not has_items"),
        ScrollingGroup(
            Select(
                Format("{item[0]}"),
                id="admin_event_registrations_select",
                item_id_getter=lambda item: item[1],
                items="items",
                on_click=show_admin_event_registration_details,
            ),
            id="admin_event_registrations_scroll",
            width=1,
            height=5,
            hide_on_single_page=True,
            when="has_items",
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="admin_event_registrations_back",
                on_click=back_to_admin_event_details,
            ),
        ),
        getter=get_admin_event_registrations,
        state=StartSG.admin_event_registrations_list,
    ),
    Window(
        Format("{title}"),
        Format("{empty_text}", when="not has_items"),
        ScrollingGroup(
            Select(
                Format("{item[0]}"),
                id="admin_pending_regs_select",
                item_id_getter=lambda item: item[1],
                items="items",
                on_click=show_pending_registration_details,
            ),
            id="admin_pending_regs_scroll",
            width=1,
            height=5,
            hide_on_single_page=True,
            when="has_items",
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="admin_pending_regs_back",
                on_click=back_to_start,
            ),
        ),
        getter=get_admin_registration_pending,
        state=StartSG.admin_registration_pending_list,
    ),
    Window(
        DynamicMedia("payment_proof_media", when="has_payment_proof_media"),
        Format("{details_text}"),
        Row(
            Button(
                text=Format("{approve_button}"),
                id="pending_reg_approve",
                on_click=approve_pending_registration,
            ),
            Button(
                text=Format("{decline_button}"),
                id="pending_reg_decline",
                on_click=decline_pending_registration,
            ),
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="pending_reg_back",
                on_click=back_to_admin_registration_pending_list,
            ),
        ),
        getter=get_admin_registration_pending_details,
        state=StartSG.admin_registration_pending_details,
    ),
)
