AGE_GROUPS = ("25-35", "35-45", "45-55", "55-65")

EVENT_AGE_GROUP_ALL = "all"
EVENT_AGE_GROUPS = (*AGE_GROUPS, EVENT_AGE_GROUP_ALL)
EVENT_PUBLISH_TARGET_BOT = "bot"
EVENT_PUBLISH_TARGET_CHANNEL = "channel"
EVENT_PUBLISH_TARGET_BOTH = "both"
EVENT_PUBLISH_TARGETS = (
    EVENT_PUBLISH_TARGET_BOT,
    EVENT_PUBLISH_TARGET_CHANNEL,
    EVENT_PUBLISH_TARGET_BOTH,
)
