from aiogram.enums import ContentType
from aiogram_dialog import Dialog, Window
from aiogram_dialog.widgets.input import MessageInput, TextInput
from aiogram_dialog.widgets.kbd import Button, Group, Row, ScrollingGroup, Select
from aiogram_dialog.widgets.media import DynamicMedia
from aiogram_dialog.widgets.text import Format

from app.bot.dialogs.events.getters import (
    get_event_address_query,
    get_event_address_select,
    get_event_age_group,
    get_event_datetime,
    get_event_description,
    get_event_image,
    get_event_name,
    get_event_preview,
    get_event_price,
)
from app.bot.dialogs.events.handlers import (
    back_from_event_address_query,
    back_from_event_age_group,
    back_from_event_datetime,
    back_from_event_description,
    back_from_event_image,
    back_from_event_name,
    back_from_event_preview,
    back_from_event_price,
    back_to_address_query,
    edit_event_address,
    edit_event_age,
    edit_event_datetime,
    edit_event_description,
    edit_event_image,
    edit_event_name,
    edit_event_price,
    ensure_partner_access,
    on_event_address_input,
    on_event_address_selected,
    on_event_age_input,
    on_event_datetime_input,
    on_event_description_input,
    on_event_name_input,
    on_event_photo_input,
    on_event_price_input,
    publish_event,
    skip_event_age,
    skip_event_price,
    skip_event_photo,
)
from app.bot.states.events import EventsSG

events_dialog = Dialog(
    Window(
        Format("{prompt}"),
        TextInput(
            id="event_name_input",
            on_success=on_event_name_input,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_name",
                on_click=back_from_event_name,
            ),
        ),
        state=EventsSG.name,
        getter=get_event_name,
    ),
    Window(
        Format("{prompt}"),
        MessageInput(
            on_event_photo_input,
            content_types=[ContentType.PHOTO],
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_image",
                on_click=back_from_event_image,
            ),
            Button(
                text=Format("{skip_button}"),
                id="skip_event_photo",
                on_click=skip_event_photo,
            ),
        ),
        state=EventsSG.image,
        getter=get_event_image,
    ),
    Window(
        Format("{prompt}"),
        TextInput(
            id="event_datetime_input",
            on_success=on_event_datetime_input,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_datetime",
                on_click=back_from_event_datetime,
            ),
        ),
        state=EventsSG.datetime,
        getter=get_event_datetime,
    ),
    Window(
        Format("{prompt}"),
        TextInput(
            id="event_address_input",
            on_success=on_event_address_input,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_address_query",
                on_click=back_from_event_address_query,
            ),
        ),
        state=EventsSG.address_query,
        getter=get_event_address_query,
    ),
    Window(
        Format("{prompt}"),
        ScrollingGroup(
            Select(
                Format("{item[0]}"),
                id="address_select",
                item_id_getter=lambda item: item[1],
                items="address_choices",
                on_click=on_event_address_selected,
            ),
            id="address_scroll",
            width=1,
            height=5,
            hide_on_single_page=True,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="address_back",
                on_click=back_to_address_query,
            ),
        ),
        state=EventsSG.address_select,
        getter=get_event_address_select,
    ),
    Window(
        Format("{prompt}"),
        TextInput(
            id="event_description_input",
            on_success=on_event_description_input,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_description",
                on_click=back_from_event_description,
            ),
        ),
        state=EventsSG.description,
        getter=get_event_description,
    ),
    Window(
        Format("{prompt}"),
        TextInput(
            id="event_price_input",
            on_success=on_event_price_input,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_price",
                on_click=back_from_event_price,
            ),
            Button(
                text=Format("{skip_button}"),
                id="skip_event_price",
                on_click=skip_event_price,
            ),
        ),
        state=EventsSG.price,
        getter=get_event_price,
    ),
    Window(
        Format("{prompt}"),
        TextInput(
            id="event_age_input",
            on_success=on_event_age_input,
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_age_group",
                on_click=back_from_event_age_group,
            ),
            Button(
                text=Format("{skip_button}"),
                id="skip_event_age",
                on_click=skip_event_age,
            ),
        ),
        state=EventsSG.age_group,
        getter=get_event_age_group,
    ),
    Window(
        DynamicMedia("preview_media"),
        Format("{preview}"),
        Group(
            Button(
                text=Format("{edit_name_button}"),
                id="edit_event_name",
                on_click=edit_event_name,
            ),
            Button(
                text=Format("{edit_image_button}"),
                id="edit_event_image",
                on_click=edit_event_image,
            ),
            Button(
                text=Format("{edit_datetime_button}"),
                id="edit_event_datetime",
                on_click=edit_event_datetime,
            ),
            Button(
                text=Format("{edit_address_button}"),
                id="edit_event_address",
                on_click=edit_event_address,
            ),
            Button(
                text=Format("{edit_description_button}"),
                id="edit_event_description",
                on_click=edit_event_description,
            ),
            Button(
                text=Format("{edit_price_button}"),
                id="edit_event_price",
                on_click=edit_event_price,
                when="is_paid",
            ),
            Button(
                text=Format("{edit_age_button}"),
                id="edit_event_age",
                on_click=edit_event_age,
            ),
            width=2,
        ),
        Row(
            Button(
                text=Format("{publish_button}"),
                id="publish_event",
                on_click=publish_event,
            ),
        ),
        Row(
            Button(
                text=Format("{back_button}"),
                id="back_from_event_preview",
                on_click=back_from_event_preview,
            ),
        ),
        state=EventsSG.preview,
        getter=get_event_preview,
    ),
    on_start=ensure_partner_access,
)
